[package]
name = "oculus-allow-dev-sideloaded"
version = "0.1.0"
edition = "2021"

[build-dependencies]
winres = "0.1.12"


[dependencies]
winreg = "0.52.0"
simplelog = { version = "0.12.2", default-features = false }
log = "0.4.24"

[package.metadata.winres]
FileDescription = "Enable Sideloaded Apps"
LegalCopyright = "Copyright © 2024 Zagrios"
CompanyName = "Zagrios"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
